# Generated by Django 4.0.4 on 2022-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '__first__'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='speciality',
            field=models.ManyToManyField(to='groups_app.speciality'),
        ),
    ]
