# Generated by Django 4.0.4 on 2022-05-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_subject_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='speciality',
            new_name='specialities',
        ),
    ]
